--- #YAML:1.0
name:               MediaWiki-EditFramework
version:            0.01
abstract:           a framework for editing MediaWiki pages.
author:
    - Steve Sanbeg <sanbeg@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MediaWiki::API:  0.17
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
